#!/usr/bin/env python3

from pathlib import Path
import subprocess

REPLACE = [
    (
        """
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = {
    self,
    nixpkgs,
  }:""",
        "};\n",
    ),
    (
        """let
    supportedSystems = ["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"];
    forEachSupportedSystem = f:
      nixpkgs.lib.genAttrs supportedSystems (system: let
        pkgs = import nixpkgs {
          inherit system;
        };
      in
        f {
          inherit pkgs;
          pkgsBuild = import nixpkgs {
            system = pkgs.stdenv.buildPlatform.system;
          };
        });""",
        "",
    ),
    (
        """in {
    packages = forEachSupportedSystem ({
      pkgs,
      pkgsBuild,
    }: let""",
        "",
    ),
    (
        """in {
      default =""",
        "in",
    ),
    ("pkgs.", ""),
    ("pkgsBuild.", ""),
    ("nixpkgs.lib", "lib"),
    (
        """});
    });

    nixosModules.kvrocks = (import ./nixos/kvrocks.nix) self;
  };
}""",
        "})",
    ),
]


def main():
    root_dir = Path(__file__).parent.resolve()

    dest_dir = root_dir / "nixpkgs/pkgs/by-name/kv/kvrocks"

    dest_dir.mkdir(parents=True, exist_ok=True)

    for i in ["dep", "version", "sha"]:
        with (
            open(root_dir / f"{i}.json", "r") as f_in,
            open(dest_dir / f"{i}.json", "w") as f_out,
        ):
            f_out.write(f_in.read().rstrip() + "\n")

    package_nix_path = dest_dir / "package.nix"
    print(f"Converting flake.nix to {package_nix_path}")

    with open(root_dir / "flake.nix", "r") as f:
        content = f.read()

    content = """# This file is generated from flake.nix by nixpkg.gen.py.
# For changes, please modify the flake.nix and the generator script.

# The dependency JSON files (dep.json, ver.json, sha.json) are generated by
# https://github.com/js0-dep/nixos-kvrocks/blob/main/update.js

{
  lib,
  stdenv,
  pkgsBuild,
  fetchFromGitHub,
  runCommand,
  autoconf,
  cmake,
  git,
  cctools,
  libiconv
}:
    let
""" + content[1:]

    for old, new in REPLACE:
        content = content.replace(old, new)

    with open(package_nix_path, "w") as f:
        f.write(content)

    print("Running nix fmt in nixpkgs...")
    subprocess.run(["nix", "fmt"], cwd=root_dir / "nixpkgs", check=True)

    print("Done.")


if __name__ == "__main__":
    main()
